const pageFiles={landing:'index.html',login:'login.html',signup:'signup.html',dashboard:'index.html',create:'create-session.html',lobby:'lobby.html','manage-writing':'writing-control.html',join:'join.html',guide:'guide.html',write:'writing.html',evaluate:'evaluation.html',result:'results.html',select:'selection.html',final:'final-result.html',demoState:'demo-state.html'};
const params=new URLSearchParams(location.search);let role=params.get('role')==='guest'?'guest':'host',selectedIdea=null;
const pageKey=Object.entries(pageFiles).find(([,file])=>file===location.pathname.split('/').pop())?.[0]||'landing';
const shellPages=!['landing','login','signup','join','guide','demoState'].includes(pageKey);
if(shellPages){
const screen=document.querySelector('.screen.active'),stage=screen?.querySelector('.stepper'),heading=screen?.querySelector('.topic-head,.work-head,.result-head,.final-hero');
if(stage&&heading)heading.insertAdjacentElement('afterend',stage);
}
const toast=document.querySelector('#toast'),modalWrap=document.querySelector('#modalWrap'),account=document.querySelector('#account');
const ideas=[
{id:1,text:'출퇴근 길에 잠깐 들러 식재료 키트를 찾아갈 수 있는 동네 무인 냉장고 서비스',values:[4,3,1]},
{id:2,text:'회의 전에 참석자의 집중 시간을 받아 안건별 적정 회의 길이를 제안하는 서비스',values:[3,4,1]},
{id:3,text:'가게별 혼잡도를 실시간으로 보여주고, 한적한 시간에 방문하면 지역 화폐 혜택을 주는 동네 상점 탐색 서비스',values:[5,2,1]},
{id:4,text:'안 쓰는 물건을 가까운 이웃과 하루 단위로 나누고, 필요한 사람에게 메시지를 보내는 서비스',values:[2,3,3]}];
function distribution(values){const total=values.reduce((a,b)=>a+b,0),labels=['↑ 좋음','— 괜찮음','↓ 별로'];return `${values.map((v,i)=>`<div class="dist-row"><span>${labels[i]}</span><div class="bar"><i style="width:${total?v/total*100:0}%"></i></div><b>${v}</b></div>`).join('')}<div class="dist-total">총 ${total}개의 평가</div>`}
function renderResults(){const resultList=document.querySelector('#resultList');if(resultList)resultList.innerHTML=ideas.map((idea,i)=>`<article class="result-card"><div><span class="eyebrow">IDEA ${String(i+1).padStart(2,'0')}</span><blockquote>${idea.text}</blockquote><div class="private">◉ 작성자는 최종 채택 전까지 비공개</div></div><div class="distribution">${distribution(idea.values)}</div></article>`).join('');const selectList=document.querySelector('#selectList');if(selectList)selectList.innerHTML=ideas.map((idea,i)=>`<article class="result-card" data-idea="${idea.id}"><div><span class="eyebrow">IDEA ${String(i+1).padStart(2,'0')}</span><blockquote>${idea.text}</blockquote><div class="private">◉ 채택 확정 후 이 아이디어의 작성자만 공개됩니다.</div></div><div class="distribution">${distribution(idea.values)}</div><button class="btn secondary pick">이 아이디어 선택</button></article>`).join('');const finalOthers=document.querySelector('#finalOthers');if(finalOthers)finalOthers.innerHTML=ideas.filter(i=>i.id!==3).map((idea,i)=>`<article class="result-card"><div><span class="eyebrow">IDEA ${String(i+1).padStart(2,'0')}</span><blockquote>${idea.text}</blockquote><div class="private">◉ 작성자 비공개</div></div><div class="distribution">${distribution(idea.values)}</div></article>`).join('');const winner=document.querySelector('.winner .distribution');if(winner)winner.innerHTML=distribution([5,2,1])}
function go(name,nextRole=role){location.href=(pageFiles[name]||pageFiles.landing)+(nextRole==='guest'?'?role=guest':'')}
function goState(state){location.href=`demo-state.html?state=${encodeURIComponent(state)}`}
function setRole(nextRole){go(nextRole==='guest'?'join':'landing',nextRole)}
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2100)}
function openModal(type){if(!modalWrap)return;const isClose=type==='close-writing';document.querySelector('#modalTitle').textContent=isClose?'작성을 조기 종료할까요?':'이 아이디어를 최종 채택할까요?';document.querySelector('#modalBody').textContent=isClose?'종료 후에는 새로 참여하거나 아이디어를 수정할 수 없어요. 저장되지 않은 입력은 반영되지 않습니다.':'최종 채택은 변경할 수 없으며, 확정 후에는 채택된 아이디어의 작성자 닉네임만 공개됩니다.';const confirm=document.querySelector('#modalConfirm');confirm.textContent=isClose?'작성 종료하고 평가 시작':'채택 확정';confirm.dataset.action=isClose?'evaluate':'final';modalWrap.hidden=false}
document.body.classList.toggle('guest-mode',role==='guest');
const demoSwitch=document.querySelector('.demo-switch');if(demoSwitch)demoSwitch.innerHTML='<details class="top-menu"><summary>데모 화면 ▾</summary><div class="menu-panel"><button data-role="host">진행자 흐름</button><button data-role="guest">참가자 흐름</button><div class="menu-subgroup"><button class="submenu-trigger" type="button" aria-haspopup="true">오류 화면 <span aria-hidden="true">▸</span></button><div class="submenu-panel"><button data-state="no-ideas">아이디어 없음</button><button data-state="join-closed">참가 불가</button><button data-state="bad-link">잘못된 공유 링크</button><button data-state="no-access">진행자 권한 없음</button><button data-state="offline">연결 끊김</button><button data-state="save-failed">저장 실패</button><button data-state="token-expired">재접속 정보 오류</button></div></div></div></details>';
if(account){account.classList.add('account-actions');account.innerHTML=['login','signup'].includes(pageKey)?'<button class="text-link" data-go="login">로그인</button>':`<span>${role==='guest'?'참가자 minji':'진행자 김모아'}</span><button class="account-logout" data-go="login">로그아웃</button>`}
const stateViews={
  'no-ideas':{eyebrow:'아이디어 없음',title:'아이디어를 모으는 데 시간이 조금 더 필요한 것 같아요.',body:'저장된 아이디어가 없어 평가 없이 안건이 종료되었어요.',action:'홈으로 돌아가기'},
  'join-closed':{eyebrow:'참가 불가',title:'참가 접수가 끝났어요.',body:'작성 단계가 끝나 새로 참여할 수 없어요. 결과가 공개되면 공유 링크에서 확인할 수 있습니다.',action:'돌아가기'},
  'bad-link':{eyebrow:'접근 오류',title:'공유 링크를 찾을 수 없어요.',body:'링크 주소를 확인해 주세요. 계속 문제가 있다면 진행자에게 새 링크를 요청해 주세요.',action:'홈으로'},
  'no-access':{eyebrow:'접근 오류',title:'이 화면에 접근할 권한이 없어요.',body:'안건을 관리하려면 해당 안건을 만든 계정으로 로그인해 주세요.',action:'홈으로'},
  'offline':{eyebrow:'연결 오류',title:'연결이 잠시 끊어졌어요.',body:'서버에서 최신 내용을 불러오지 못했어요. 이전에 저장한 내용은 유지됩니다.',action:'다시 시도'},
  'save-failed':{eyebrow:'저장 실패',title:'입력한 내용을 저장하지 못했어요.',body:'화면에 입력한 내용은 남아 있어요. 연결을 확인한 뒤 다시 저장해 주세요.',action:'다시 저장'},
  'token-expired':{eyebrow:'재접속 오류',title:'이전 참여 기록을 불러올 수 없어요.',body:'이 브라우저의 재접속 정보가 유효하지 않습니다. 진행자에게 문의해 주세요.',action:'홈으로'}
};
if(pageKey==='demoState'){const key=stateViews[params.get('state')]?params.get('state'):'bad-link',view=stateViews[key];document.querySelector('#stateEyebrow').textContent=view.eyebrow;document.querySelector('#stateTitle').textContent=view.title;document.querySelector('#stateBody').textContent=view.body;const action=document.querySelector('#stateAction');action.textContent=view.action;if(['offline','save-failed'].includes(key)){action.removeAttribute('data-go');action.dataset.state=key}else{action.dataset.go='landing'}}
document.addEventListener('click',e=>{const stateButton=e.target.closest('[data-state]');if(stateButton)goState(stateButton.dataset.state);const goButton=e.target.closest('[data-go]');if(goButton)go(goButton.dataset.go);const roleButton=e.target.closest('[data-role]');if(roleButton)setRole(roleButton.dataset.role);const toastButton=e.target.closest('[data-toast]');if(toastButton)showToast(toastButton.dataset.toast);const modalButton=e.target.closest('[data-modal]');if(modalButton)openModal(modalButton.dataset.modal);if(e.target.closest('[data-close-modal]')&&modalWrap)modalWrap.hidden=true;const rating=e.target.closest('[data-rating]');if(rating){document.querySelectorAll('[data-rating]').forEach(b=>b.classList.remove('selected'));rating.classList.add('selected');const state=document.querySelector('#ratingState');if(state)state.textContent=`‘${rating.dataset.rating}’을 선택했어요. 저장해야 반영돼요.`}const pick=e.target.closest('.pick');if(pick){const card=pick.closest('[data-idea]');selectedIdea=Number(card.dataset.idea);document.querySelectorAll('[data-idea]').forEach(c=>{const active=Number(c.dataset.idea)===selectedIdea;c.classList.toggle('selected',active);c.querySelector('.pick').textContent=active?'✓ 선택됨':'이 아이디어 선택'});document.querySelector('#selectionSummary').textContent=`IDEA ${String(selectedIdea).padStart(2,'0')} · ${ideas.find(i=>i.id===selectedIdea).text.slice(0,34)}…`;document.querySelector('#confirmSelection').disabled=false}});
const modalConfirm=document.querySelector('#modalConfirm');if(modalConfirm)modalConfirm.addEventListener('click',e=>go(e.currentTarget.dataset.action));renderResults();
